server:
  port: ${PORT:8080}

spring:
  application:
    name: deepJava

  datasource:
    url: jdbc:h2:mem:portfoliodb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, heapdump, info, prometheus
  endpoint:
    heapdump:
      enabled: true
  metrics:
    enable:
      jvm: true