INSERT IGNORE INTO project (id, title, category, summary, content, github, tags) VALUES
(1,
 'JVM 힙 메모리 분석기',
 'JVM',
 'Java 애플리케이션의 힙 메모리 사용량을 실시간으로 모니터링하고 GC 이벤트를 시각화하는 CLI 도구입니다.',
 '## 프로젝트 개요\nJVM의 힙 메모리 구조(Young/Old Generation)를 이해하고 GC 동작을 분석하기 위해 개발한 도구입니다.\n\n## 주요 기능\n- JVM Attach API를 활용한 실시간 힙 모니터링\n- GC 이벤트(Minor/Major GC) 감지 및 로깅\n- 메모리 누수 탐지를 위한 객체 참조 추적\n- VisualVM 연동 지원\n\n## 기술적 도전\nJVM Attach API는 같은 OS 사용자 권한이 필요하여, Docker 환경에서 권한 문제를 해결하는 과정이 까다로웠습니다. `sun.tools.attach.HotSpotVirtualMachine`을 직접 다루며 JVM 내부 동작을 깊이 이해할 수 있었습니다.\n\n## 성과\n- GC 중단 시간 35% 감소\n- 프로덕션 메모리 누수 2건 탐지 및 수정',
 'https://github.com/HyeonSeong/jvm-heap-analyzer',
 'Java,JVM,GC,Memory,Monitoring'),
(2,
 'OS 스케줄러 시뮬레이터',
 'OS Kernel',
 'FCFS, SJF, Round Robin, Priority 등 주요 CPU 스케줄링 알고리즘을 시뮬레이션하고 성능 지표를 비교하는 도구입니다.',
 '## 프로젝트 개요\n운영체제 수업에서 배운 CPU 스케줄링 알고리즘을 직접 구현하고 성능을 비교 분석한 프로젝트입니다.\n\n## 구현 알고리즘\n- **FCFS** (First Come First Served)\n- **SJF** (Shortest Job First - Preemptive/Non-Preemptive)\n- **Round Robin** (Time Quantum 설정 가능)\n- **Priority Scheduling** (Aging 기법 포함)\n- **Multilevel Queue**\n\n## 기술적 도전\nPreemptive SJF(SRTF) 구현 시 Context Switch 오버헤드를 정확히 모델링하는 것이 어려웠습니다. 실제 Linux 커널의 CFS(Completely Fair Scheduler) 소스 코드를 참고하여 vruntime 개념을 반영했습니다.\n\n## 성과\n- 각 알고리즘별 평균 대기시간, 반환시간, CPU 이용률 자동 계산\n- Gantt 차트 시각화 출력\n- 100개 프로세스 기준 시뮬레이션 시간 < 50ms',
 'https://github.com/HyeonSeong/os-scheduler-simulator',
 'C,OS,Kernel,Scheduling,Algorithm'),
(3,
 'G1GC vs ZGC 성능 벤치마크',
 'JVM',
 'G1GC와 ZGC의 처리량, 지연시간, Stop-The-World 구간을 JMH 벤치마크로 정밀 측정하고 튜닝 가이드를 작성한 프로젝트입니다.',
 '## 프로젝트 개요\nJava 21 환경에서 G1GC와 ZGC의 실제 성능 차이를 측정하고 워크로드별 최적 GC 설정을 도출했습니다.\n\n## 측정 항목\n- **처리량(Throughput)**: ops/sec\n- **평균 지연시간(Latency)**: p50 / p95 / p99\n- **STW(Stop-The-World) 구간**: GC 로그 파싱\n- **힙 메모리 효율**: 동일 힙 크기 대비 Old Gen 점유율\n\n## 주요 발견\n| 항목 | G1GC | ZGC |\n|---|---|---|\n| 처리량 | 높음 | 중간 |\n| p99 지연 | ~100ms | < 10ms |\n| STW | 수십~수백ms | < 1ms |\n\n## 결론 및 튜닝 가이드\n지연 시간이 중요한 서비스(게임, 금융)는 ZGC, 배치/처리량이 중요한 서비스는 G1GC가 적합합니다.\n`-XX:MaxGCPauseMillis`, `-XX:G1HeapRegionSize` 등 핵심 플래그 정리 포함.',
 'https://github.com/HyeonSeong/gc-benchmark',
 'Java,JVM,GC,G1GC,ZGC,JMH,Performance,Benchmark');
